### PR TITLE
document table enhancement

### PR DESCRIPTION
**Pull request by flutistar**
#23120

- [x] Fixed issue on clicking (x) button on dropdown filter
- [x] Added 3 characters delay into input fields
- [x] Added sort direction
- [x] Document Type - Sentence Case

image

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://documents-ui-dev--pr-72-rthu6m96.web.app

**Review by doug-lovett — APPROVED** [review]
Very nice.

**Review by cameron-eyds — APPROVED** [review]
Looking great, nice work!

**Pull request merged**
