### PR TITLE
Convert filing date as optional

### PR DESCRIPTION
**Pull request by flutistar**
#23264

- [x] Converted `Filing Date` field to optional.

### Create Document

image

### Result on the table

image

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
Fanstastico!

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://documents-ui-dev--pr-76-x28avo9s.web.app

**Pull request merged**
