### PR TITLE
Document services CI/CD.

### PR DESCRIPTION
**Pull request by pwei1018**
[/bcgov/entity/22854](https://app.zenhub.com/workspaces/connect-6690070c1ee5ec09f20a0ec1/issues/gh/bcgov/entity/22854)

Description:

1. Documents UI CI/CD;
2. Doc API CI/CD;

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
Looks good to me!

**Review by doug-lovett — APPROVED** [review]
LGTM.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://documents-ui-dev--pr-36-vo6vwmfw.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://documents-ui-dev--pr-36-vo6vwmfw.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://documents-ui-dev--pr-36-vo6vwmfw.web.app

**Pull request merged**
