### PR TITLE
added break lines into entity type drop down

### PR DESCRIPTION
**Pull request by flutistar**
#22806

[x] Add break lines for each registry on entity type dropdown
[x] Empty `Filing Date` on first load
[x] Replace `pdf download` svg

image

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://documents-ui-dev--pr-67-q1tin4u9.web.app

**Review by cameron-eyds — APPROVED** [review]
Looks great sir, don't stress about the iterations. 
It's always going to happen!

**Review by doug-lovett — APPROVED** [review]
The gift that keeps on giving.

**Pull request merged**
