### PR TITLE
updated styles on document edit

### PR DESCRIPTION
**Pull request by flutistar**
#23412

- [x] Updated paddings on cancellation modal
- [x] Added (x) button on scanning date
- [x] Updated Document class dropdown on edit document
- [x] Removed bg color on `ghost` buttons

image

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
Looks great!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://documents-ui-dev--pr-74-hz7wev72.web.app

**Review by doug-lovett — APPROVED** [review]
Looks great.

**Pull request merged**
