### PR TITLE
DRS Route Protection and Misc UI Bugs

### PR DESCRIPTION
**Pull request by cameron-eyds**
- Fixes Downloading Documents from DRS Table
- Fixes Review and Submission for Manual Document Indexing
- Fix ScrollTo calling additional pages
- Includes global route protection - restricting to STAFF only

### CODE REVIEW

**Review by flutistar — APPROVED** [review]
Looks good

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://documents-ui-dev--pr-101-4rso2iks.web.app

**Review by doug-lovett — APPROVED** [review]
Fantastico!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://documents-ui-dev--pr-101-4rso2iks.web.app

**Pull request merged**
