### PR TITLE
Documents Upload Refactors and Edit

### PR DESCRIPTION
**Pull request by cameron-eyds**
#22858

- Refactors the Document Upload component to modern design (Updates included in Document Indexing)
- Refactored for Editing
- Implements Document Uploads into Document Record Edit
- Unit testing

Screenshot 2024-09-05 at 7 45 36 AM
Screenshot 2024-09-05 at 7 45 07 AM

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://documents-ui-dev--pr-41-zchpy5ml.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good.

**Review by flutistar — APPROVED** [review]
Looks good!

**Pull request merged**
