### PR TITLE
View and Edit Document Records Re-Work

### PR DESCRIPTION
**Pull request by cameron-eyds**
#23412 
- Edit Record Updates - navigation and additional fields
- Change tracking, validations and badges

#22857
- Scanning Edit forms

#22860
- submission handling to create/edit scanning
- edit record Documents or Meta Data

Various unit test updates

Screenshot 2024-10-02 at 1 00 11 PM
Screenshot 2024-10-02 at 1 00 06 PM
Screenshot 2024-10-02 at 12 59 18 PM
Screenshot 2024-10-02 at 12 59 05 PM

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://documents-ui-dev--pr-66-y25hi530.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://documents-ui-dev--pr-66-y25hi530.web.app

**Review by doug-lovett — APPROVED** [review]
Outstanding

**Review by flutistar — APPROVED** [review]
LGTM

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://documents-ui-dev--pr-66-y25hi530.web.app

**Pull request merged**
