### PR TITLE
24734 removed duplicated doc types

### PR DESCRIPTION
**Pull request by flutistar**
*Issue #:* /bcgov/entity#24734
*Description of changes:*
- Fixed issue on updating document record (no document list)
- Ignore 404 error for scanning details

### CODE REVIEW

**Review by cameron-eyds — APPROVED** [review]
LGTM!!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://documents-ui-dev--pr-100-jwc3f470.web.app

**Review by doug-lovett — APPROVED** [review]
Looks good to me too.

**Pull request merged**
